name: weight-loss-consultant-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ maxtrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install npm dependencies
        run: npm ci
        
      - name: Lint ReactJS UI code
        run: lint:ui
      
      - name: Lint NestJS Gateway code
        run: lint:gateway
        
      - name: Lint NestJS Users Management code
        run: npm run lint:users-mgnt-api
      
      - name: Lint NestJS Health Management code
        run: npm run lint:health-mgnt-api
        
      - name: Lint NestJS Scheduling Management code
        run: npm run lint:scheduling-api
        
      - name: Test ReactJS UI code
        run: npm run test:ui
        
      - name: Test ReactJS UI e2e code
        run: npm run test-e2e:uo
        
      - name: Test NestJS Gateway code
        run: npm run test:gateway
        
      - name: Test NestJS Users Management code
        run: npm run test:users-mgnt-api
        
      - name: Test NestJS Health Management code
        run: npm run test:health-mgnt-api
        
      - name: Test NestJS Scheduling Management code
        run: test:scheduling-api
